# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:15.0.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    parallelism: 3
    resource_class: large

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: chmod +x gradlew

      # Download and cache dependencies
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - gradle-repo-v1-{{ .Branch }}-{{ checksum ".cache/dependencies.lockfile" }}
            - gradle-repo-v1-{{ .Branch }}-
            - gradle-repo-v1-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.cache
          key: gradle-repo-v1-{{ .Branch }}-{{ checksum ".cache/dependencies.lockfile" }}

      # run tests!
      - run: ./gradlew test -Pthread$CIRCLE_NODE_INDEX
      - store_test_results:
          path: ./build/test-results/test
      - store_artifacts:
          path: ./build/reports

  mutations:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:15.0.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
      parallelism: 5
      resource_class: large

      working_directory: ~/repo

      environment:
        # Customize the JVM maximum heap limit
        JVM_OPTS: -Xmx3200m
        TERM: dumb

    steps:
      - checkout
      - run: chmod +x gradlew
      - run: ./gradlew dependencies

      - run: ./gradlew pitest -Pthread$CIRCLE_NODE_INDEX
      - store_test_results:
          path: ./build/test-results/test
      - store_artifacts:
          path: ./build/reports
    requires:
      - build