# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  jacoco:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:17.0.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    parallelism: 5
    resource_class: large

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: chmod +x gradlew

      - run: ./gradlew dependencies

      # run tests!
      - run: ./gradlew test -Pthread$CIRCLE_NODE_INDEX
      - store_test_results:
          path: ./build/test-results/test
      - store_artifacts:
          path: ./build/reports
  pitest:
    docker:
     - image: cimg/openjdk:17.0.2
    parallelism: 6
    resource_class: large

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
     - checkout
     - run: chmod +x gradlew
     - run: ./gradlew dependencies

     - run: ./gradlew pitest -Pthread$CIRCLE_NODE_INDEX
     - store_artifacts:
         path: ./build/reports

workflows:
  version: 2
  workflow:
    jobs:
      - jacoco
      - pitest